// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NeuronaLabs.Database;

#nullable disable

namespace NeuronaLabs.Migrations
{
    [DbContext(typeof(NeuronaLabsDbContext))]
    [Migration("20251118222711_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NeuronaLabs.Domain.DiagnosticRecord", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DiagnosisText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("ID");

                    b.HasIndex("PatientId");

                    b.ToTable("DiagnosticRecords");
                });

            modelBuilder.Entity("NeuronaLabs.Domain.Patient", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("LastDiagnosisID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("LastDiagnosisID");

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("NeuronaLabs.Domain.DiagnosticRecord", b =>
                {
                    b.HasOne("NeuronaLabs.Domain.Patient", "Patient")
                        .WithMany("DiagnosticRecords")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("NeuronaLabs.Domain.Patient", b =>
                {
                    b.HasOne("NeuronaLabs.Domain.DiagnosticRecord", "LastDiagnosis")
                        .WithMany()
                        .HasForeignKey("LastDiagnosisID")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("LastDiagnosis");
                });

            modelBuilder.Entity("NeuronaLabs.Domain.Patient", b =>
                {
                    b.Navigation("DiagnosticRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
